### ISSUE TITLE
Comparison with CFT modules

### ISSUE THREAD

**Issue by braderhart** [terraform-google-modules/cloud-foundation-fabric#207]
In the README you mention that this is used for prototyping/testing, but also mention production usage. I also see:

> If you are looking for a feature-rich black box to manage project or product creation with minimal specific skills, you might be better served by the Cloud Foundation Toolkit suite of modules.

I'm a bit confused personally about this project. In many ways it seems this project is getting more updates, and has better support for things like confidential compute on VM instances, which the CFT VM instance module doesn't even though it is GA. There may be other examples of things not supported by the other CFT modules that are supported here.

The Terraform templates link [here](https://cloud.google.com/foundation-toolkit) links to this repo being used as a starting point as an end-to-end example:

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/docs/terraform.md#examples

It would be good to know what the future plan is of this project vs the CFT suite of modules as you explain it. Are they going to continue to co-exist? Is this project suitable for production usage as well, and not just prototyping/testing? I don't find the CFT suite of modules to be any simpler in terms of usage, nor containing more features that I'm aware of (but I could be wrong).

It would be helpful to get a better explanation. I could see Google renaming the Cloud Foundation Toolkit to Cloud Foundation Fabric and abandoning one over the other. What would be the preferred route to go if you are concerned about longevity and frequent updates to keep the modules feature-compatible with the official resources in the Google provider?

**Comment by ludoo** [comment]
Hey Brad, thanks for the kind words. I cannot speak for the other CFT module authors of course, but since Fabric and CFT were both started roughly at the same time, and we have customers using both, I don't think it will be easy to favor Fabric and deprecate CFT.

What I can assure you is that we're actively maintaing Fabric, not only because it's often the basis we use to kickstart automation for customers, but also because many people in my team use it for study and prototyping.
